[package]
name = "wasmdev"
version = "0.1.0"
edition = "2021"
description = "A rust web development server library"
license = "MIT"
email = "robingronberg@gmail.com"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
