[package]
name = "wasmdev_macro"
version = "0.1.1"
edition = "2021"
description = "wasmev macro implementation"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.49"
quote = "1.0.23"
wasmdev_server = { workspace = true }