[package]
name = "wasmdev"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmdev_macro = { workspace = true}

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
wasmdev_server = { workspace = true}
