[package]
name = "wasmdev"
version = "0.1.0"
edition = "2021"
description = "A rust web development server library"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
wasmdev_server = { workspace = true }
xshell = "0.2.3"
proc-macro2 = "1.0.49"
quote = "1.0.23"