[package]
name = "simple"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmdev = { workspace = true }

[dependencies.web-sys]
version = "0.3.4"
features = [
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window',
]